services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: taski-back
    restart: unless-stopped
    env_file:
      - ./back/.env
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - ./back:/app/
    networks:
      - taski-network

  db:
    image: mysql:8.0
    container_name: taski-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file:
      - ./back/.env
    environment:
      MYSQL_DATABASE: taski
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - taski-network

  adminer:
    image: adminer
    restart: unless-stopped
    environment:
      - ADMINER_DESIGN=dracula
    ports:
      - '8080:8080'
    networks:
      - taski-network
    

  front:
    build: 
      context: ./front
      dockerfile: Dockerfile
    container_name: taski-front
    ports:
      - '5173:5173'
    depends_on:
      - back
      - db
    restart: unless-stopped
    env_file:
      - ./front/.env
    volumes:
      - ./front:/app/
      -  taski_front_modules:/app/node_modules
    networks:
      - taski-network

volumes:
  mysql_data:
  taski_front_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./front/node_modules

networks:
  taski-network: